# llvm, soda-opt, tensorflow, torch-mlir, etc.
export LLVM_INSTALL_DIR=/opt/llvm-project
export PATH=${LLVM_INSTALL_DIR}/bin:${PATH}

export OPENROAD_INSTALL_DIR=/opt/openroad/OpenROAD
export PATH=${OPENROAD_INSTALL_DIR}/bin:${PATH}

export PANDA_INSTALL_DIR=/opt/panda
export PATH=${PANDA_INSTALL_DIR}/bin:${PATH}

export SODA_OPT_INSTALL_DIR=/opt/soda-opt
export PATH=${SODA_OPT_INSTALL_DIR}/bin:${PATH}

export TENSORFLOW_INSTALL_DIR=/opt/tensorflow
export PATH=${TENSORFLOW_INSTALL_DIR}/bin:${PATH}

export TORCH_MLIR_INSTALL_DIR=/opt/torch-mlir
export PATH=${TORCH_MLIR_INSTALL_DIR}/bin:${PATH}

export YOSYS_INSTALL_DIR=/opt/openroad/yosys
export PATH=${YOSYS_INSTALL_DIR}/bin:${PATH}

# python path
export PYTHONPATH=:${LLVM_INSTALL_DIR}/python_packages/mlir_core:${TORCH_MLIR_INSTALL_DIR}/python_packages/torch_mlir:${SODA_OPT_INSTALL_DIR}/python_packages/soda

echo "Setting up X forwarding"
XAUTH=/home/soda-opt-user/env/.Xauthority
if test -f "$XAUTH"; then
    echo "Setting XAUTHORITY to $XAUTH"
    export XAUTHORITY=$XAUTH
else
    echo "File $XAUTH not found. Skipping X forwarding."
fi
